# Module 1. Introduction

## 3. Quick Python Course

## Index
* [1. Introduction](#section1)
    * [1.1. Packages](#section11)
    * [1.2. Importing Libraries](#section12)
    * [2. Python Syntax](#section2)
        * [2.1. Assignment](#section21)
        * [2.2. Flow Control](#section22)
        * [2.3. Data Structures](#section23)
    * [3. Numpy Course](#section3)
    * [4. Matplotlib Course](#section4)
    * [5. Pandas Course](#section5)

# 1. Introduction

You don't need to be a Python developer to start using the Python ecosystem for machine learning. As a developer who already knows how to program in one or more programming languages, you can learn a new language like Python very quickly. You just need to know some language properties to transfer what you already know to the new language.

# 2. Python Syntax

When starting in Python, you need to know some key details about the language syntax to be able to read and understand Python code.

## 2.1. Assignment

As a programmer, assignment and types shouldn't surprise you.

### Strings

In [1]:
# Save a string to a variable and print the character at position 0, length, and the whole string
data = 'hello world'
print(data[0])
print(len(data))
print(data)

h
11
hello world


### Numbers

In [2]:
# Save a number, print it, change its value, and print it again
value1 = 123.1
value2 = 10
print(value1)
print(value2)

123.1
10


### Booleans

In [4]:
# Save the two boolean values in two different variables and print them
a = True
b = False
print(a,b)

True False


### Multiple Assignment

In [5]:
# Assign 3 numbers to 3 variables and print them
a,b,c = 1,2,3
print(a,b,c)

1 2 3


### None Value

In [6]:
a = None
print(a)

None


## 2.2. Flow Control

Flow control is common to every programming language, so you already know what they do. The only thing you need to learn is the syntax.

### If-else

In [7]:
# Save a value and verify if its 99, greater tahn 200 and neither
value = 99
if value==99:
    print('That is fast')
elif value > 200:
    print('That is too fast')
else:
    print('That is safe')

That is fast


### For-Loops

`for` loops until the condition is done

In [9]:
# Print values from 1 to 10 
for i in range(10):
    print(i+1)

1
2
3
4
5
6
7
8
9
10


### While-Loops

`while` loops until the condition is done

In [11]:
# Print values from 1 to 10  with while
i = 0
while i < 10:
    print(i+1)
    i+=1

1
2
3
4
5
6
7
8
9
10


## 2.3. Data Structures

There are 3 most used data structures. There are tuples, lists and dictionaries

### Tuples

Tuples are read-only collection of items

In [14]:
# Save in a tuple 3 values to print
a = (1,2,3,4)
print(a)

(1, 2, 3, 4)


### Lists

Lists use bracket notation and can be indexed using array notation. 

In [26]:
# Create a list with three values, print the first one, add a fourth, print the length, and all elements
my_list = [1,2,3]
print(my_list)
print(f"Zeroth value: {my_list[0]}")
my_list.append(10)
print(f"List length: {len(my_list)}")
print(f"Last value: {my_list[3]}")
for value in my_list:
    print(value)

[1, 2, 3]
Zeroth value: 1
List length: 4
Last value: 10
1
2
3
10


### Dictionaries

Dictionaries are mappings of names to values, like key-value pairs. Note the use of brackets and colons when defining the dictionary.

In [32]:
# Create a dictionary with 3 values, print the first one, change its value
# Show the keys and values of the dictionary, and finally, print all values with a loop\n",
dict = {'a':1, 'b':2 , 'c':3}
print(f"A value: {dict['a']}")
dict['a'] = 10
print(f"A value: {dict['a']}")
print(f"Keys: {dict.keys()}")
print(f"Values: {dict.values()}")

for i in dict.keys():
    print(dict[i])

A value: 1
A value: 10
Keys: dict_keys(['a', 'b', 'c'])
Values: dict_values([10, 2, 3])
10
2
3


### Functions

The biggest problem with Python is whitespace. Make sure to have a new empty line after the indented code. The following example defines a new function to sum two values and calls the function with two arguments.

In [35]:
# Create a function that sums two values
def mysum(x,y):
    return x+y

result = mysum(2,3)
print(result)

5


# 3. Numpy Course

NumPy provides the basic data structures and operations for SciPy. These are arrays (ndarrays) that are efficient for defining and manipulating.

### Create an array

See how we easily convert a Python list into a NumPy array

In [38]:
# Create an array and print their values y length

import numpy as np

mylist= [1,2,3]
myarray = np.array(mylist)
print(myarray)
print(myarray.shape)

[1 2 3]
(3,)


### Data Access

Array notation and slicing can be used to efficiently access data in a NumPy array.

In [47]:
# Make a 2x3 matrix and print the first and last list
# Then print a specific element and the values of column

import numpy as np

mylist = [[1,2,3],[4,5,6]]
myarray = np.array(mylist)
print(myarray)
print(myarray.shape)
print(f"First row: {myarray[0]}")
print(f"Last row: {myarray[-1]}")
print(f"Value[0][2]: {myarray[0,2]}")
print(f"Whole col: {myarray[:,2]}")

[[1 2 3]
 [4 5 6]]
(2, 3)
First row: [1 2 3]
Last row: [4 5 6]
Value[0][2]: 3
Whole col: [3 6]


### Arithmetic Operators

NumPy arrays can be directly used in arithmetic.

In [50]:
# Create two vectors to suma and multiple

import numpy as np

myarray1 = np.array([2,2,2])
myarray2 = np.array([3,3,3])

print(f"Addition: {myarray1 + myarray2}")
print(f"Multiplication: {myarray1 * myarray2}")

Addition: [5 5 5]
Multiplication: [6 6 6]


There's much more to NumPy arrays, but these examples give you an idea of the efficiencies they provide when working with lots of numerical data. Refer to Chapter 24 for resources to learn more about the NumPy API.

For more information on this library:
   * [NumPy Documentation](https://docs.scipy.org/doc/numpy/user/)
   * [SciPy Documentation](http://scipy-lectures.org/)

# 4. Matplotlib Course

Matplotlib can be used to create diagrams and plots. The library is generally used as follows:
  * Call a plotting function with some data (e.g., `.plot()`)
  * Call many functions to configure plot properties (e.g., labels and colors).
  * Make the plot visible (e.g., `.show()`

### Line Graphs

The following example creates a simple line diagram from one-dimensional data.

In [ ]:
# Create a vector and plot a line graph with its values.
import matplotlib.pyplot as ptl
import numpy as np

myarray = np.array([1,2,3])